CREATE TABLE "audit_log" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "audit_log_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"actor_id" integer NOT NULL,
	"action" text NOT NULL,
	"subject" text NOT NULL,
	"detail" text,
	"at" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "bets" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "bets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ticket_no" text NOT NULL,
	"player_id" integer NOT NULL,
	"match_id" integer NOT NULL,
	"line_id" integer NOT NULL,
	"side" text NOT NULL,
	"stake_mmk" bigint NOT NULL,
	"score_home_at_bet" integer NOT NULL,
	"score_away_at_bet" integer NOT NULL,
	"placed_at" text NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"net_mmk" bigint,
	"fee_mmk" bigint,
	"settled_at" text,
	"settlement_id" integer,
	"voided_by" integer,
	"void_reason" text,
	CONSTRAINT "bets_ticket_no_unique" UNIQUE("ticket_no")
);
--> statement-breakpoint
CREATE TABLE "invite_codes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "invite_codes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"code" text NOT NULL,
	"max_uses" integer NOT NULL,
	"used_count" integer DEFAULT 0 NOT NULL,
	"expires_at" text NOT NULL,
	"created_by" integer NOT NULL,
	"kind" text DEFAULT 'admin' NOT NULL,
	CONSTRAINT "invite_codes_code_unique" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "lines" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "lines_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"match_id" integer NOT NULL,
	"market" text DEFAULT 'ah' NOT NULL,
	"version" integer NOT NULL,
	"fav_side" text NOT NULL,
	"ball_q" integer NOT NULL,
	"price_c" integer NOT NULL,
	"status" text NOT NULL,
	"posted_by" integer NOT NULL,
	"posted_at" text NOT NULL,
	CONSTRAINT "lines_match_id_market_version_unique" UNIQUE("match_id","market","version")
);
--> statement-breakpoint
CREATE TABLE "match_days" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "match_days_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"date" text NOT NULL,
	"status" text DEFAULT 'open' NOT NULL,
	"closed_at" text,
	CONSTRAINT "match_days_date_unique" UNIQUE("date")
);
--> statement-breakpoint
CREATE TABLE "matches" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "matches_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"stage" text NOT NULL,
	"home_team" text NOT NULL,
	"away_team" text NOT NULL,
	"kickoff_utc" text NOT NULL,
	"venue" text NOT NULL,
	"match_day" text NOT NULL,
	"status" text DEFAULT 'scheduled' NOT NULL,
	"home_score" integer,
	"away_score" integer,
	"score_confirmed_at" text,
	"bet_limit_mmk" bigint,
	"external_api_id" text
);
--> statement-breakpoint
CREATE TABLE "players" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "players_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"phone" text NOT NULL,
	"pin_hash" text NOT NULL,
	"display_name" text NOT NULL,
	"role" text DEFAULT 'player' NOT NULL,
	"language" text DEFAULT 'en' NOT NULL,
	"failed_pin_attempts" integer DEFAULT 0 NOT NULL,
	"locked_until" text,
	"must_change_pin" boolean DEFAULT false NOT NULL,
	"session_epoch" integer DEFAULT 0 NOT NULL,
	"created_at" text NOT NULL,
	"referred_by" integer,
	CONSTRAINT "players_phone_unique" UNIQUE("phone")
);
--> statement-breakpoint
CREATE TABLE "settings" (
	"id" integer PRIMARY KEY NOT NULL,
	"daily_total_limit_mmk" bigint DEFAULT 0 NOT NULL,
	"default_personal_invite_uses" integer DEFAULT 10 NOT NULL,
	"referral_bonus_mmk" bigint DEFAULT 0 NOT NULL,
	"commission_pct" integer DEFAULT 3 NOT NULL,
	"discount_pct" integer DEFAULT 2 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "settlements" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "settlements_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ref" text NOT NULL,
	"match_day_id" integer NOT NULL,
	"player_id" integer NOT NULL,
	"net_mmk" bigint NOT NULL,
	"marked_by" integer NOT NULL,
	"marked_at" text NOT NULL,
	"payment_method" text,
	"payment_reference" text,
	"remark" text,
	CONSTRAINT "settlements_ref_unique" UNIQUE("ref"),
	CONSTRAINT "settlements_match_day_id_player_id_unique" UNIQUE("match_day_id","player_id")
);
--> statement-breakpoint
ALTER TABLE "bets" ADD CONSTRAINT "bets_player_id_players_id_fk" FOREIGN KEY ("player_id") REFERENCES "public"."players"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bets" ADD CONSTRAINT "bets_match_id_matches_id_fk" FOREIGN KEY ("match_id") REFERENCES "public"."matches"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bets" ADD CONSTRAINT "bets_line_id_lines_id_fk" FOREIGN KEY ("line_id") REFERENCES "public"."lines"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bets" ADD CONSTRAINT "bets_settlement_id_settlements_id_fk" FOREIGN KEY ("settlement_id") REFERENCES "public"."settlements"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bets" ADD CONSTRAINT "bets_voided_by_players_id_fk" FOREIGN KEY ("voided_by") REFERENCES "public"."players"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invite_codes" ADD CONSTRAINT "invite_codes_created_by_players_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."players"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lines" ADD CONSTRAINT "lines_match_id_matches_id_fk" FOREIGN KEY ("match_id") REFERENCES "public"."matches"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lines" ADD CONSTRAINT "lines_posted_by_players_id_fk" FOREIGN KEY ("posted_by") REFERENCES "public"."players"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "players" ADD CONSTRAINT "players_referred_by_players_id_fk" FOREIGN KEY ("referred_by") REFERENCES "public"."players"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "settlements" ADD CONSTRAINT "settlements_match_day_id_match_days_id_fk" FOREIGN KEY ("match_day_id") REFERENCES "public"."match_days"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "settlements" ADD CONSTRAINT "settlements_player_id_players_id_fk" FOREIGN KEY ("player_id") REFERENCES "public"."players"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "settlements" ADD CONSTRAINT "settlements_marked_by_players_id_fk" FOREIGN KEY ("marked_by") REFERENCES "public"."players"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "invite_personal_uq" ON "invite_codes" USING btree ("created_by") WHERE kind = 'personal';