import { describe, it, expect } from "vitest";
import { gradeBet, gradeDetail, type GradeInput } from "./grade";

type Row = { name: string } & GradeInput & { status: string; net: number };
const T: Row[] = [
  // BODY (ah)
  {
    name: "MEX -1 @0.30 win by 2",
    market: "ah",
    side: "fav",
    ballQ: 4,
    priceC: 30,
    stake: 200_000,
    effFav: 2,
    effDog: 0,
    status: "won",
    net: 200_000,
  },
  {
    name: "MEX -1 @0.30 win by 1 (on line)",
    market: "ah",
    side: "fav",
    ballQ: 4,
    priceC: 30,
    stake: 200_000,
    effFav: 1,
    effDog: 0,
    status: "won",
    net: 60_000,
  },
  {
    name: "MEX -1 @0.30 draw -> lose all",
    market: "ah",
    side: "fav",
    ballQ: 4,
    priceC: 30,
    stake: 200_000,
    effFav: 0,
    effDog: 0,
    status: "lost",
    net: -200_000,
  },
  {
    name: "KOR -0 @1.00 won by 1",
    market: "ah",
    side: "fav",
    ballQ: 0,
    priceC: 100,
    stake: 4_000_000,
    effFav: 2,
    effDog: 1,
    status: "won",
    net: 4_000_000,
  },
  {
    name: "CZE +0 @1.00 lost by 1",
    market: "ah",
    side: "dog",
    ballQ: 0,
    priceC: 100,
    stake: 200_000,
    effFav: 2,
    effDog: 1,
    status: "lost",
    net: -200_000,
  },
  {
    name: "Brazil -0.75 @0.90 win by 2",
    market: "ah",
    side: "fav",
    ballQ: 3,
    priceC: 90,
    stake: 100_000,
    effFav: 2,
    effDog: 0,
    status: "won",
    net: 100_000,
  },
  {
    name: "Brazil -0.75 win by 1",
    market: "ah",
    side: "fav",
    ballQ: 3,
    priceC: 90,
    stake: 100_000,
    effFav: 1,
    effDog: 0,
    status: "won",
    net: 100_000,
  },
  {
    name: "Brazil -0.75 draw -> lose 0.75",
    market: "ah",
    side: "fav",
    ballQ: 3,
    priceC: 90,
    stake: 100_000,
    effFav: 0,
    effDog: 0,
    status: "lost",
    net: -75_000,
  },
  {
    name: "Brazil -0.75 lose by 1 -> lose all",
    market: "ah",
    side: "fav",
    ballQ: 3,
    priceC: 90,
    stake: 100_000,
    effFav: 0,
    effDog: 1,
    status: "lost",
    net: -100_000,
  },
  // body on-line direction: underdog WIN, level LOSE
  {
    name: "dog +1 @0.30 opp won by exactly 1 (on line) -> win price",
    market: "ah",
    side: "dog",
    ballQ: 4,
    priceC: 30,
    stake: 100_000,
    effFav: 1,
    effDog: 0,
    status: "won",
    net: 30_000,
  },
  {
    name: "level fav @0.50 draw (on line) -> lose price",
    market: "ah",
    side: "fav",
    ballQ: 0,
    priceC: 50,
    stake: 100_000,
    effFav: 0,
    effDog: 0,
    status: "lost",
    net: -50_000,
  },
  {
    name: "level dog @0.50 draw (on line) -> lose price",
    market: "ah",
    side: "dog",
    ballQ: 0,
    priceC: 50,
    stake: 100_000,
    effFav: 0,
    effDog: 0,
    status: "lost",
    net: -50_000,
  },
  // GOALS (ou)
  {
    name: "Over 2.0 @0.50 total 2 (on line) S200k -> lose price",
    market: "ou",
    side: "over",
    ballQ: 8,
    priceC: 50,
    stake: 200_000,
    effFav: 2,
    effDog: 0,
    status: "lost",
    net: -100_000,
  },
  {
    name: "Over 2.0 @0.50 total 2 (on line) S4M -> lose price",
    market: "ou",
    side: "over",
    ballQ: 8,
    priceC: 50,
    stake: 4_000_000,
    effFav: 2,
    effDog: 0,
    status: "lost",
    net: -2_000_000,
  },
  {
    name: "Over 2.0 @0.35 total 3 -> full win",
    market: "ou",
    side: "over",
    ballQ: 8,
    priceC: 35,
    stake: 200_000,
    effFav: 2,
    effDog: 1,
    status: "won",
    net: 200_000,
  },
  {
    name: "Under 2.0 @0.35 total 3 -> lose all",
    market: "ou",
    side: "under",
    ballQ: 8,
    priceC: 35,
    stake: 2_000_000,
    effFav: 2,
    effDog: 1,
    status: "lost",
    net: -2_000_000,
  },
  {
    name: "Over 2.25 @0.90 total 3 -> full win",
    market: "ou",
    side: "over",
    ballQ: 9,
    priceC: 90,
    stake: 100_000,
    effFav: 3,
    effDog: 0,
    status: "won",
    net: 100_000,
  },
  {
    name: "Over 2.25 @0.90 total 2 -> lose 0.25",
    market: "ou",
    side: "over",
    ballQ: 9,
    priceC: 90,
    stake: 100_000,
    effFav: 2,
    effDog: 0,
    status: "lost",
    net: -25_000,
  },
  {
    name: "Over 2.25 @0.90 total 1 -> lose all",
    market: "ou",
    side: "over",
    ballQ: 9,
    priceC: 90,
    stake: 100_000,
    effFav: 1,
    effDog: 0,
    status: "lost",
    net: -100_000,
  },
  {
    name: "Under 2.0 @0.40 total 2 (on line) -> win price",
    market: "ou",
    side: "under",
    ballQ: 8,
    priceC: 40,
    stake: 100_000,
    effFav: 1,
    effDog: 1,
    status: "won",
    net: 40_000,
  },
  // rounding (half-away-from-zero, once)
  {
    name: "half-loss odd stake: Bra -0.5 draw 33,333 -> -16,667",
    market: "ah",
    side: "fav",
    ballQ: 2,
    priceC: 90,
    stake: 33_333,
    effFav: 0,
    effDog: 0,
    status: "lost",
    net: -16_667,
  },
  {
    name: "on-line price odd: MEX -1 @0.33 win by1 33,333 -> +11,000",
    market: "ah",
    side: "fav",
    ballQ: 4,
    priceC: 33,
    stake: 33_333,
    effFav: 1,
    effDog: 0,
    status: "won",
    net: 11_000,
  },
  {
    name: "partial-loss odd: Over2.25 total2 99,999 -> -25,000",
    market: "ou",
    side: "over",
    ballQ: 9,
    priceC: 90,
    stake: 99_999,
    effFav: 2,
    effDog: 0,
    status: "lost",
    net: -25_000,
  },
  // FIX 1: on-line rounding — .5 must round away from zero
  {
    name: "on-line round .5 up: ah fav @0.69 stake 150 -> +104",
    market: "ah",
    side: "fav",
    ballQ: 4,
    priceC: 69,
    stake: 150,
    effFav: 1,
    effDog: 0,
    status: "won",
    net: 104,
  },
  {
    name: "on-line round .5 lose: ou over @0.69 stake 150 -> -104",
    market: "ou",
    side: "over",
    ballQ: 8,
    priceC: 69,
    stake: 150,
    effFav: 2,
    effDog: 0,
    status: "lost",
    net: -104,
  },
];

describe("gradeBet (A3 even-money model)", () => {
  for (const c of T)
    it(c.name, () => {
      const r = gradeBet({
        market: c.market,
        side: c.side,
        ballQ: c.ballQ,
        priceC: c.priceC,
        stake: c.stake,
        effFav: c.effFav,
        effDog: c.effDog,
      } as GradeInput);
      expect(r.status).toBe(c.status);
      expect(r.netMmk).toBe(c.net);
    });

  it("gradeDetail.netMmk === gradeBet.netMmk for all rows", () => {
    for (const c of T) {
      const d = gradeDetail({
        market: c.market,
        side: c.side,
        ballQ: c.ballQ,
        priceC: c.priceC,
        stake: c.stake,
        effFav: c.effFav,
        effDog: c.effDog,
      } as GradeInput);
      expect(d.netMmk).toBe(c.net);
      expect(d.status).toBe(c.status);
    }
  });

  it("kinds", () => {
    expect(
      gradeDetail({
        market: "ah",
        side: "fav",
        ballQ: 4,
        priceC: 30,
        stake: 100_000,
        effFav: 2,
        effDog: 0,
      } as GradeInput).kind,
    ).toBe("full_win");
    expect(
      gradeDetail({
        market: "ah",
        side: "fav",
        ballQ: 4,
        priceC: 30,
        stake: 100_000,
        effFav: 1,
        effDog: 0,
      } as GradeInput).kind,
    ).toBe("on_line_win");
    expect(
      gradeDetail({
        market: "ou",
        side: "over",
        ballQ: 8,
        priceC: 50,
        stake: 100_000,
        effFav: 2,
        effDog: 0,
      } as GradeInput).kind,
    ).toBe("on_line_lose");
    expect(
      gradeDetail({
        market: "ou",
        side: "over",
        ballQ: 9,
        priceC: 90,
        stake: 100_000,
        effFav: 2,
        effDog: 0,
      } as GradeInput).kind,
    ).toBe("partial_lose");
    expect(
      gradeDetail({
        market: "ah",
        side: "fav",
        ballQ: 4,
        priceC: 30,
        stake: 100_000,
        effFav: 0,
        effDog: 0,
      } as GradeInput).kind,
    ).toBe("full_lose");
  });

  it("rejects bad inputs", () => {
    expect(() =>
      gradeBet({
        market: "ah",
        side: "fav",
        ballQ: 4,
        priceC: 0,
        stake: 1000,
        effFav: 0,
        effDog: 0,
      } as GradeInput),
    ).toThrow(); // price 0
    expect(() =>
      gradeBet({
        market: "ah",
        side: "fav",
        ballQ: 4,
        priceC: -30,
        stake: 1000,
        effFav: 0,
        effDog: 0,
      } as GradeInput),
    ).toThrow(); // negative price
    expect(() =>
      gradeBet({
        market: "ah",
        side: "fav",
        ballQ: 4,
        priceC: 101,
        stake: 1000,
        effFav: 0,
        effDog: 0,
      } as GradeInput),
    ).toThrow();
    expect(() =>
      gradeBet({
        market: "ah",
        side: "fav",
        ballQ: -1,
        priceC: 30,
        stake: 1000,
        effFav: 0,
        effDog: 0,
      } as GradeInput),
    ).toThrow();
    expect(() =>
      gradeBet({
        market: "ah",
        side: "over" as never,
        ballQ: 4,
        priceC: 30,
        stake: 1000,
        effFav: 0,
        effDog: 0,
      } as GradeInput),
    ).toThrow(); // side/market mismatch
  });
});
